### PR TITLE
Dark mode support

### PR DESCRIPTION
**Pull request by pppery**
Per request at https://meta.wikimedia.org/wiki/MediaWiki_talk:Gadget-MoreMenu.js

### CODE REVIEW

**Comment by nacaru-w** [comment]
@pppery the correction should also apply to users using the vector-2022 version of the tool's CSS, so the change should also be applied in line 428 [here](https://github.com/wikimedia-gadgets/MoreMenu/blob/master/src/MoreMenu.js#L428).

**Comment by pppery** [comment]
Thanks. Done.

**Comment by nacaru-w** [comment]
@MusikAnimal do you have a moment to merge this and transclude it its meta page?

**Comment by MusikAnimal** [comment]
Sorry for taking so long to get to this! I'll get this deployed today. Thanks @pppery for the PR :)

**Pull request merged**
